name: compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install wxWidgets
      run: sudo apt install -y libwxgtk3.0-dev

    - name: Install CMake
      run: sudo apt install -y cmake

    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    
    - name: cmake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: make
      run: |
        cd build
        make
        [ -f lib/libfractalapp.a ] || exit 1